spring.application.name=case-itau-autorizador

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/accountsdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

aws.sqs.queueUrl=${AWS_SQS_QUEUEURL:http://localhost:4566/000000000000/conta-bancaria-criada}
aws.sqs.endpoint=${AWS_SQS_ENDPOINT:http://localhost:4566}
aws.sqs.accessKey=${AWS_SQS_ACCESSKEY:test}
aws.sqs.secretKey=${AWS_SQS_SECRETKEY:test}

jpa.hibernate.ddl-auto=none
jpa.properties.hibernate.format_sql=true
jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jpa.show-sql=true

management.endpoints.web.exposure.include=prometheus
management.metrics.tags.application=case-itau-autorizador

sqs.poller.count=5
transaction.max-retries=3
