spring.application.name=case-itau-autorizador

spring.datasource.url=jdbc:postgresql://localhost:5432/accountsdb
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

aws.sqs.queueUrl=http://localhost:4566/000000000000/my-queue
aws.sqs.endpoint=http://localhost:4566
aws.sqs.accessKey=test
aws.sqs.secretKey=test

jpa.hibernate.ddl-auto=none
jpa.properties.hibernate.format_sql=true
jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jpa.show-sql=true