{
 "title": "Autorizador Dashboard",
 "tags": [
  "springboot",
  "micrometer",
  "prometheus"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Successful Transactions",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    { "expr": "transactions_success_total" }
   ]
  },
  {
   "title": "Failed Transactions",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "targets": [
    { "expr": "transactions_failed_total" }
   ]
  },
  {
   "title": "Transactions Per Second",
   "type": "graph",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "rate(transactions_success_total[1m])"
    }
   ]
  },
  {
   "title": "HTTP Requests Per Second",
   "type": "graph",
   "gridPos": { "x": 0, "y": 10, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "Database Query Time (avg)",
   "type": "graph",
   "gridPos": { "x": 0, "y": 28, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "avg(rate(hikaricp_connections_acquire_seconds_sum[1m]) / rate(hikaricp_connections_acquire_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "SQS Messages Available",
   "type": "graph",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 6 },
   "targets": [
    { "expr": "sqs_messages_visible" }
   ]
  },
  {
   "title": "SQS Messages In-flight",
   "type": "graph",
   "gridPos": { "x": 0, "y": 10, "w": 12, "h": 6 },
   "targets": [
    { "expr": "sqs_messages_inflight" }
   ]
  },
  {
   "title": "SQS Messages Delayed",
   "type": "graph",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 6 },
   "targets": [
    { "expr": "sqs_messages_delayed" }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "graph",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 6 },
   "targets": [
    { "expr": "jvm_memory_used_bytes" }
   ]
  },
  {
   "title": "System CPU Usage",
   "type": "graph",
   "gridPos": { "x": 0, "y": 22, "w": 12, "h": 6 },
   "targets": [
    { "expr": "system_cpu_usage" }
   ]
  }
 ]
}